{{ codegen.generate_source(
    schema_name='<name_of_your_schema>', 
    database_name=target.database,
    table_names=none,
    generate_columns=False,
    include_descriptions=True,
    include_data_types=True,
    table_pattern='%',
    exclude='',
    name=schema_name,
    include_database=False,
    include_schema=False,
    case_sensitive_databases=False,
    case_sensitive_schemas=False,
    case_sensitive_tables=False,
    case_sensitive_cols=False) }}
